### ISSUE TITLE
Fail to upload boost big header

### ISSUE THREAD

**Issue by fausturs** [buildbarn/bb-deployments#101]
When I try build my project, I got 

```
ERROR: /data/myname/work/test/2023/2023-10-17/basis/BUILD:67:11: Compiling sbase/models/kv/zmap.cpp failed: (Exit 34): 6 errors during bulk transfer:
java.io.IOException: Error while uploading artifact with digest '6a0cc14b6acc6b7e3b6e4b3feb8886844eb57ebb87fbcd24042c220cecadf9d4/1193960'
java.io.IOException: Error while uploading artifact with digest '102292b1aeafa3928c2f345a0da6a6fe2b3b99c7dd65eb957df3c36dffec7798/1602653'
java.io.IOException: Error while uploading artifact with digest 'e33be885f01e4a828eee2397194577c390ed1fbd23c5e0879b1e8ac619e36d42/1956836'
java.io.IOException: Error while uploading artifact with digest '9bbe3936f7a8c7d5d33e57d26bcc3edb40eef44b23d7495ae09cc93b424fad5c/2328744'
java.io.IOException: Error while uploading artifact with digest 'baa46cddf79e51d5201fb7764a7fba505e4e8fd108e3e23b20bc7f43e99e131a/1367011'
java.io.IOException: Error while uploading artifact with digest '49199a0bc4890b48bab688db5abe1e69f34f4339affd24778104c10b80d7a179/1249715'
```

and sometimes I got 
```
                at io.grpc.Status.asRuntimeException(Status.java:535)
                ... 10 more
        Suppressed: java.io.IOException: Error while uploading artifact with digest 'e33be885f01e4a828eee2397194577c390ed1fbd23c5e0879b1e8ac619e36d42/1956836'
                at com.google.devtools.build.lib.remote.ByteStreamUploader.lambda$uploadBlobAsync$0(ByteStreamUploader.java:171)
                at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:203)
                at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:190)
                at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
                ... 57 more
        Caused by: io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 413
invalid content-type: text/html
headers: Metadata(:status=413,server=SGW,date=Fri, 20 Oct 2023 03:56:27 GMT,content-type=text/html,content-length=176)
DATA-----------------------------
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

from the `execution_log_json_file`, I found the artifact in the error output.
```
  {
    "path": "external/boost~1.80.0/include/boost/geometry/srs/projections/epsg_traits.hpp",
    "digest": {
      "hash": "e33be885f01e4a828eee2397194577c390ed1fbd23c5e0879b1e8ac619e36d42",
      "sizeBytes": "1956836",
      "hashFunctionName": "SHA-256"
    }
```

They are boost headers, which are too big.
May I ask, which component sets the threshold for this size? buildbarn? bazel? Or is it my nginx proxy?

What should I do to make my task work properly?

BTW, I have try modify the "size bytes" settings in https://github.com/buildbarn/bb-deployments/blob/master/kubernetes/config/common.yaml. But It seems not work for me.

**Comment by EdSchouten** [comment]
This is likely your nginx proxy.
